//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCCLvl2
    {
        public int AccCCLvl2ID { get; set; }
        public string CCLvl2Name { get; set; }
        public string CCLvl2Code { get; set; }
    }
}
