//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTypeExpens
    {
        public int AccTypeExpensesID { get; set; }
        public string ExpName { get; set; }
        public string ExpCode { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
