//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AMCATE
    {
        public string CATEID { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string CATENAME { get; set; }
        public string CATEDESC { get; set; }
        public int NXATNO { get; set; }
        public string NOTES { get; set; }
        public string SEGCODE { get; set; }
        public short DEFFLAG { get; set; }
        public string DEFACCT { get; set; }
        public short INACTIVE { get; set; }
        public decimal DATEINACTV { get; set; }
        public decimal DATELASTMN { get; set; }
        public int NXTBCODENO { get; set; }
    }
}
