//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRTA
    {
        public string TERMSCODE { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string CODEDESC { get; set; }
        public short SWACTV { get; set; }
        public decimal DATEINACTV { get; set; }
        public decimal DATELASTMN { get; set; }
        public short SWMULTPAYM { get; set; }
        public short CODEVAT { get; set; }
        public short CODEDISTYP { get; set; }
        public decimal DISDAYSTR1 { get; set; }
        public decimal DISDAYSTR2 { get; set; }
        public decimal DISDAYSTR3 { get; set; }
        public decimal DISDAYSTR4 { get; set; }
        public decimal DISDAYEND1 { get; set; }
        public decimal DISDAYEND2 { get; set; }
        public decimal DISDAYEND3 { get; set; }
        public decimal DISDAYEND4 { get; set; }
        public decimal DISMTHADD1 { get; set; }
        public decimal DISMTHADD2 { get; set; }
        public decimal DISMTHADD3 { get; set; }
        public decimal DISMTHADD4 { get; set; }
        public decimal DISDAYUSE1 { get; set; }
        public decimal DISDAYUSE2 { get; set; }
        public decimal DISDAYUSE3 { get; set; }
        public decimal DISDAYUSE4 { get; set; }
        public short CODEDUETYP { get; set; }
        public decimal DUEDAYSTR1 { get; set; }
        public decimal DUEDAYSTR2 { get; set; }
        public decimal DUEDAYSTR3 { get; set; }
        public decimal DUEDAYSTR4 { get; set; }
        public decimal DUEDAYEND1 { get; set; }
        public decimal DUEDAYEND2 { get; set; }
        public decimal DUEDAYEND3 { get; set; }
        public decimal DUEDAYEND4 { get; set; }
        public decimal DUEMTHADD1 { get; set; }
        public decimal DUEMTHADD2 { get; set; }
        public decimal DUEMTHADD3 { get; set; }
        public decimal DUEMTHADD4 { get; set; }
        public decimal DUEDAYUSE1 { get; set; }
        public decimal DUEDAYUSE2 { get; set; }
        public decimal DUEDAYUSE3 { get; set; }
        public decimal DUEDAYUSE4 { get; set; }
        public decimal CNTENTERED { get; set; }
        public decimal PCTDUETOT { get; set; }
    }
}
