//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APVEN()
        {
            this.POVUPRs = new HashSet<POVUPR>();
        }
    
        public string VENDORID { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string SHORTNAME { get; set; }
        public string IDGRP { get; set; }
        public short SWACTV { get; set; }
        public decimal DATEINAC { get; set; }
        public decimal DATELASTMN { get; set; }
        public short SWHOLD { get; set; }
        public decimal DATESTART { get; set; }
        public string IDPPNT { get; set; }
        public string VENDNAME { get; set; }
        public string TEXTSTRE1 { get; set; }
        public string TEXTSTRE2 { get; set; }
        public string TEXTSTRE3 { get; set; }
        public string TEXTSTRE4 { get; set; }
        public string NAMECITY { get; set; }
        public string CODESTTE { get; set; }
        public string CODEPSTL { get; set; }
        public string CODECTRY { get; set; }
        public string NAMECTAC { get; set; }
        public string TEXTPHON1 { get; set; }
        public string TEXTPHON2 { get; set; }
        public string PRIMRMIT { get; set; }
        public string IDACCTSET { get; set; }
        public string CURNCODE { get; set; }
        public string RATETYPE { get; set; }
        public string BANKID { get; set; }
        public short PRTSEPCHKS { get; set; }
        public string DISTSETID { get; set; }
        public string DISTCODE { get; set; }
        public string GLACCNT { get; set; }
        public string TERMSCODE { get; set; }
        public short DUPINVCCD { get; set; }
        public short DUPAMTCODE { get; set; }
        public short DUPDATECD { get; set; }
        public string CODETAXGRP { get; set; }
        public short TAXCLASS1 { get; set; }
        public short TAXCLASS2 { get; set; }
        public short TAXCLASS3 { get; set; }
        public short TAXCLASS4 { get; set; }
        public short TAXCLASS5 { get; set; }
        public short TAXRPTSW { get; set; }
        public short SUBJTOWTHH { get; set; }
        public string TAXNBR { get; set; }
        public short TAXIDTYPE { get; set; }
        public short TAXNOTE2SW { get; set; }
        public string CLASID { get; set; }
        public decimal AMTCRLIMT { get; set; }
        public decimal AMTBALDUET { get; set; }
        public decimal AMTBALDUEH { get; set; }
        public decimal AMTPPDINVT { get; set; }
        public decimal AMTPPDINVH { get; set; }
        public decimal DTLASTRVAL { get; set; }
        public decimal AMTBALLARV { get; set; }
        public decimal CNTOPENINV { get; set; }
        public decimal CNTPPDINVC { get; set; }
        public decimal CNTINVPAID { get; set; }
        public decimal DAYSTOPAY { get; set; }
        public decimal DATEINVCHI { get; set; }
        public decimal DATEBALHI { get; set; }
        public decimal DATEINVHIL { get; set; }
        public decimal DATEBALHIL { get; set; }
        public decimal DATELASTAC { get; set; }
        public decimal DATELASTIV { get; set; }
        public decimal DATELASTCR { get; set; }
        public decimal DATELASTDR { get; set; }
        public decimal DATELASTPA { get; set; }
        public decimal DATELASTDI { get; set; }
        public decimal DATELSTADJ { get; set; }
        public string IDINVCHI { get; set; }
        public string IDINVCHILY { get; set; }
        public decimal AMTINVHIT { get; set; }
        public decimal AMTBALHIT { get; set; }
        public decimal AMTWTHTCUR { get; set; }
        public decimal AMTINVHILT { get; set; }
        public decimal AMTBALHILT { get; set; }
        public decimal AMTWTHLYTC { get; set; }
        public decimal AMTLASTIVT { get; set; }
        public decimal AMTLASTCRT { get; set; }
        public decimal AMTLASTDRT { get; set; }
        public decimal AMTLASTPYT { get; set; }
        public decimal AMTLASTDIT { get; set; }
        public decimal AMTLASTADT { get; set; }
        public decimal AMTINVHIH { get; set; }
        public decimal AMTBALHIH { get; set; }
        public decimal AMTWTHHCUR { get; set; }
        public decimal AMTINVHILH { get; set; }
        public decimal AMTBALHILH { get; set; }
        public decimal AMTWTHLYHC { get; set; }
        public decimal AMTLASTIVH { get; set; }
        public decimal AMTLASTCRH { get; set; }
        public decimal AMTLASTDRH { get; set; }
        public decimal AMTLASTPYH { get; set; }
        public decimal AMTLASTDIH { get; set; }
        public decimal AMTLASTADH { get; set; }
        public string PAYMCODE { get; set; }
        public string IDTAXREGI1 { get; set; }
        public string IDTAXREGI2 { get; set; }
        public string IDTAXREGI3 { get; set; }
        public string IDTAXREGI4 { get; set; }
        public string IDTAXREGI5 { get; set; }
        public short SWDISTBY { get; set; }
        public string CODECHECK { get; set; }
        public decimal AVGDAYSPAY { get; set; }
        public decimal AVGPAYMENT { get; set; }
        public decimal AMTINVPDHC { get; set; }
        public decimal AMTINVPDTC { get; set; }
        public decimal CNTNBRCHKS { get; set; }
        public short SWTXINC1 { get; set; }
        public short SWTXINC2 { get; set; }
        public short SWTXINC3 { get; set; }
        public short SWTXINC4 { get; set; }
        public short SWTXINC5 { get; set; }
        public string EMAIL1 { get; set; }
        public string EMAIL2 { get; set; }
        public string WEBSITE { get; set; }
        public string CTACPHONE { get; set; }
        public string CTACFAX { get; set; }
        public short DELMETHOD { get; set; }
        public decimal RTGPERCENT { get; set; }
        public short RTGDAYS { get; set; }
        public string RTGTERMS { get; set; }
        public decimal RTGAMTTC { get; set; }
        public decimal RTGAMTHC { get; set; }
        public int VALUES { get; set; }
        public int NEXTCUID { get; set; }
        public string LEGALNAME { get; set; }
        public short CHK1099AMT { get; set; }
        public string IDCUST { get; set; }
        public string BRN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POVUPR> POVUPRs { get; set; }
    }
}
