//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class APVENO
    {
        public string VENDORID { get; set; }
        public string OPTFIELD { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string VALUE { get; set; }
        public short TYPE { get; set; }
        public short LENGTH { get; set; }
        public short DECIMALS { get; set; }
        public short ALLOWNULL { get; set; }
        public short VALIDATE { get; set; }
        public short SWSET { get; set; }
    }
}
