//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCategory_Mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetCategory_Mst()
        {
            this.CPRFAsset_Mst = new HashSet<CPRFAsset_Mst>();
        }
    
        public int AssetCatId { get; set; }
        public string AssetCatCode { get; set; }
        public string AssetCatDesc { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPRFAsset_Mst> CPRFAsset_Mst { get; set; }
    }
}
