//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditCPRF_log
    {
        public int AuditCPRF_id { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ActionBtn { get; set; }
        public string ColumnStr { get; set; }
        public string ValueStr { get; set; }
        public Nullable<int> CPRF_Id { get; set; }
        public Nullable<int> CPRFDt_Id { get; set; }
        public Nullable<int> PRId { get; set; }
        public string Remarks { get; set; }
    }
}
