//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCentre_Mst
    {
        public int CostCentreId { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string CostCentreStr { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    
        public virtual AccTypeDept AccTypeDept { get; set; }
        public virtual CprfArea_Mst CprfArea_Mst { get; set; }
        public virtual Process_Mst Process_Mst { get; set; }
    }
}
