//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRFBudget_Mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPRFBudget_Mst()
        {
            this.CPRF_File = new HashSet<CPRF_File>();
            this.CPRFAsset_Mst = new HashSet<CPRFAsset_Mst>();
            this.CPRFBudget_Dtls = new HashSet<CPRFBudget_Dtls>();
        }
    
        public int CPRF_Id { get; set; }
        public string CPRF_No { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string Category { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public string ProjectOwner { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Status { get; set; }
        public Nullable<int> BudgetUtilYear { get; set; }
        public string ProjectJustification { get; set; }
        public string Benefits { get; set; }
        public string HOD { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> SendToHod { get; set; }
        public Nullable<System.DateTime> SendToIE { get; set; }
        public string HODName { get; set; }
        public string HODRejectReason { get; set; }
        public Nullable<System.DateTime> SendToCoo { get; set; }
        public string IEName { get; set; }
        public string IERejectReason { get; set; }
        public Nullable<System.DateTime> SendToGMD { get; set; }
        public string COOName { get; set; }
        public string COORejectReason { get; set; }
        public Nullable<System.DateTime> SendToProcessIE { get; set; }
        public string GMDName { get; set; }
        public string GMDRejectReason { get; set; }
        public Nullable<System.DateTime> CPRFcompleteDate { get; set; }
        public string IECPRFCompleteName { get; set; }
        public string IEKIVName { get; set; }
        public string IEKIVReason { get; set; }
        public Nullable<System.DateTime> IEKIVDate { get; set; }
        public string CatMain { get; set; }
        public string InvestTerm { get; set; }
        public Nullable<bool> LockFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPRF_File> CPRF_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPRFAsset_Mst> CPRFAsset_Mst { get; set; }
        public virtual Usr_mst Usr_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPRFBudget_Dtls> CPRFBudget_Dtls { get; set; }
    }
}
