//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRFBudget_Dtls
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPRFBudget_Dtls()
        {
            this.CPRFAsset_Mst = new HashSet<CPRFAsset_Mst>();
        }
    
        public int CPRFDt_Id { get; set; }
        public Nullable<int> CPRF_Id { get; set; }
        public Nullable<int> CPRFDt_Id_Refer { get; set; }
        public string CPRFDt_No { get; set; }
        public Nullable<int> CPRF_Lvl { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalBudget { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string CostCentreStr { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<int> AssetStatus { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> Exchange { get; set; }
        public Nullable<decimal> TotalBudgetMYR { get; set; }
        public Nullable<decimal> BalanceMYR { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> AssetCatId { get; set; }
    
        public virtual AccTypeDept AccTypeDept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPRFAsset_Mst> CPRFAsset_Mst { get; set; }
        public virtual CPRFBudget_Mst CPRFBudget_Mst { get; set; }
        public virtual CprfCategory_Mst CprfCategory_Mst { get; set; }
    }
}
