//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRFAsset_Mst
    {
        public int AssetId { get; set; }
        public Nullable<int> CPRFDt_Id { get; set; }
        public Nullable<int> CPRF_Id { get; set; }
        public string AssetNo { get; set; }
        public string AssetSystemNo { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> AssetCatId { get; set; }
        public Nullable<System.DateTime> EstPrDate { get; set; }
        public Nullable<bool> DelistReqFlag { get; set; }
        public string DelistReqBy { get; set; }
        public Nullable<System.DateTime> DelistReqDate { get; set; }
        public string DelistUnlockBy { get; set; }
        public Nullable<System.DateTime> DelistUnlockDate { get; set; }
        public Nullable<bool> MatchFlag { get; set; }
        public string MatchBy { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public string PRSNumbering { get; set; }
        public string AssetDesc { get; set; }
        public string CostCentre { get; set; }
        public string Area { get; set; }
        public string Requestor { get; set; }
        public string PONo { get; set; }
        public string SerialNo { get; set; }
        public string MachineID { get; set; }
        public string AssetTagStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual CPRFBudget_Mst CPRFBudget_Mst { get; set; }
        public virtual AssetCategory_Mst AssetCategory_Mst { get; set; }
        public virtual CPRFBudget_Dtls CPRFBudget_Dtls { get; set; }
    }
}
