//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPRFMst
    {
        public int CPRFId { get; set; }
        public string CPRFNo { get; set; }
        public Nullable<decimal> CPRFBudget { get; set; }
        public Nullable<decimal> CPRFBalance { get; set; }
    }
}
