//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCCD
    {
        public string CURID { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string CURNAME { get; set; }
        public string SYMBOL { get; set; }
        public short DECIMALS { get; set; }
        public short SYMBOLPOS { get; set; }
        public string THOUSSEP { get; set; }
        public string DECSEP { get; set; }
        public short NEGDISP { get; set; }
    }
}
