//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCRD
    {
        public string HOMECUR { get; set; }
        public string RATETYPE { get; set; }
        public string SOURCECUR { get; set; }
        public decimal RATEDATE { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public decimal RATE { get; set; }
        public decimal SPREAD { get; set; }
        public short DATEMATCH { get; set; }
        public short RATEOPER { get; set; }
    }
}
