//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Domi_PurEntities : DbContext
    {
        public Domi_PurEntities()
            : base("name=Domi_PurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audlgn_Log> Audlgn_Log { get; set; }
        public virtual DbSet<Department_mst> Department_mst { get; set; }
        public virtual DbSet<Lgn_mst> Lgn_mst { get; set; }
        public virtual DbSet<Menu_mst> Menu_mst { get; set; }
        public virtual DbSet<Position_mst> Position_mst { get; set; }
        public virtual DbSet<SubMenu_mst> SubMenu_mst { get; set; }
        public virtual DbSet<Usr_mst> Usr_mst { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<RoleMenuMapping_mst> RoleMenuMapping_mst { get; set; }
    
        public virtual ObjectResult<usp_GetMenuData_Result> usp_GetMenuData(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMenuData_Result>("usp_GetMenuData", userIdParameter);
        }
    
        public virtual int AssignRoleMenuMap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AssignRoleMenuMap");
        }
    }
}
