//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICCategory_Mst
    {
        public int IC_id { get; set; }
        public string IC_CategoryCode { get; set; }
        public string IC_Desc { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
