//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ICITMV
    {
        public string ITEMNO { get; set; }
        public short VENDTYPE { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string VENDNUM { get; set; }
        public string VENDNAME { get; set; }
        public string VENDITEM { get; set; }
        public string VENDCONT { get; set; }
        public string VENDCNCY { get; set; }
        public decimal VENDCOST { get; set; }
        public short VENDEXISTS { get; set; }
        public decimal FACTOR { get; set; }
        public string COSTUNIT { get; set; }
        public decimal QTYMINORD { get; set; }
    
        public virtual POVUPR POVUPR { get; set; }
    }
}
