//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastNoMst
    {
        public int LastNoId { get; set; }
        public string Initial { get; set; }
        public Nullable<int> DocType { get; set; }
        public Nullable<int> DocYear { get; set; }
        public Nullable<int> LastNo { get; set; }
    }
}
