//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_mst()
        {
            this.RoleMenuMapping_mst = new HashSet<RoleMenuMapping_mst>();
        }
    
        public int Menu_id { get; set; }
        public string Menu_name { get; set; }
        public string Menu_url { get; set; }
        public Nullable<int> Menu_ParentId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ordering { get; set; }
        public Nullable<int> MenuLayer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMenuMapping_mst> RoleMenuMapping_mst { get; set; }
    }
}
