//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_mst
    {
        public int Menu_id { get; set; }
        public string Menu_name { get; set; }
        public string Menu_url { get; set; }
        public Nullable<int> Menu_ParentId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Ordering { get; set; }
    }
}
