//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBudget
    {
        public int BudgetId { get; set; }
        public Nullable<int> DepId { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual AccTypeDept AccTypeDept { get; set; }
        public virtual Month Month1 { get; set; }
    }
}
