//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyBudget_Mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthlyBudget_Mst()
        {
            this.MonthlyBudget_Expense = new HashSet<MonthlyBudget_Expense>();
        }
    
        public int BudgetId { get; set; }
        public string BudgetCode { get; set; }
        public string Section { get; set; }
        public string Area { get; set; }
        public string Expenses { get; set; }
        public Nullable<bool> StockFlag { get; set; }
        public Nullable<decimal> StockInitial { get; set; }
        public Nullable<bool> NonStockFlag { get; set; }
        public Nullable<decimal> NonStockInitial { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyBudget_Expense> MonthlyBudget_Expense { get; set; }
    }
}
