//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyDeptBudget
    {
        public int MDB_Id { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<bool> StockFlag { get; set; }
        public Nullable<decimal> StockInitial { get; set; }
        public Nullable<bool> NonStockFlag { get; set; }
        public Nullable<decimal> NonStockInitial { get; set; }
        public Nullable<decimal> AdditionStock { get; set; }
        public Nullable<decimal> AdditionNonStock { get; set; }
        public Nullable<decimal> ConsumptionStock { get; set; }
        public Nullable<decimal> ConsumptionNonStock { get; set; }
        public Nullable<decimal> BalanceStock { get; set; }
        public Nullable<decimal> BalanceNonStock { get; set; }
        public Nullable<int> MonthOf { get; set; }
        public Nullable<int> YearOf { get; set; }
    
        public virtual MonthlyBudget_Mst MonthlyBudget_Mst { get; set; }
    }
}
