//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class POVUPR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POVUPR()
        {
            this.ICITMVs = new HashSet<ICITMV>();
        }
    
        public string ITEMNO { get; set; }
        public string VDCODE { get; set; }
        public decimal AUDTDATE { get; set; }
        public decimal AUDTTIME { get; set; }
        public string AUDTUSER { get; set; }
        public string AUDTORG { get; set; }
        public string VCPDESC { get; set; }
        public short BCOSTTYPE { get; set; }
        public decimal BAMOUNT { get; set; }
        public string DEFBUNIT { get; set; }
        public decimal BASECONV { get; set; }
        public short SCOSTTYPE { get; set; }
        public short SDEFUSING { get; set; }
        public decimal SPERCENT { get; set; }
        public decimal SDAMOUNT { get; set; }
        public decimal SFAMOUNT { get; set; }
        public string DEFSUNIT { get; set; }
        public decimal SALECONV { get; set; }
        public decimal SALESTART { get; set; }
        public decimal SALEEND { get; set; }
        public short COSTFMT { get; set; }
        public decimal COSTQTY0 { get; set; }
        public decimal COSTQTY1 { get; set; }
        public decimal COSTQTY2 { get; set; }
        public decimal COSTQTY3 { get; set; }
        public decimal COSTQTY4 { get; set; }
        public decimal COSTQTY5 { get; set; }
        public decimal COSTQTY6 { get; set; }
        public decimal COSTQTY7 { get; set; }
        public decimal COSTQTY8 { get; set; }
        public decimal COSTQTY9 { get; set; }
        public decimal PRCNTLVL0 { get; set; }
        public decimal PRCNTLVL1 { get; set; }
        public decimal PRCNTLVL2 { get; set; }
        public decimal PRCNTLVL3 { get; set; }
        public decimal PRCNTLVL4 { get; set; }
        public decimal PRCNTLVL5 { get; set; }
        public decimal PRCNTLVL6 { get; set; }
        public decimal PRCNTLVL7 { get; set; }
        public decimal PRCNTLVL8 { get; set; }
        public decimal PRCNTLVL9 { get; set; }
        public decimal AMOUNTLVL0 { get; set; }
        public decimal AMOUNTLVL1 { get; set; }
        public decimal AMOUNTLVL2 { get; set; }
        public decimal AMOUNTLVL3 { get; set; }
        public decimal AMOUNTLVL4 { get; set; }
        public decimal AMOUNTLVL5 { get; set; }
        public decimal AMOUNTLVL6 { get; set; }
        public decimal AMOUNTLVL7 { get; set; }
        public decimal AMOUNTLVL8 { get; set; }
        public decimal AMOUNTLVL9 { get; set; }
        public short ROUNDMETHD { get; set; }
        public decimal ROUNDAMT { get; set; }
    
        public virtual APVEN APVEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICITMV> ICITMVs { get; set; }
    }
}
