//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_Mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PR_Mst()
        {
            this.PR_Details = new HashSet<PR_Details>();
            this.PRFiles = new HashSet<PRFile>();
            this.PO_Mst = new HashSet<PO_Mst>();
        }
    
        public int PRId { get; set; }
        public string PRNo { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StatId { get; set; }
        public Nullable<int> PRTypeId { get; set; }
        public string FIleName { get; set; }
        public string FilePath { get; set; }
        public string HODApprovalBy { get; set; }
        public Nullable<System.DateTime> HODApprovalDate { get; set; }
        public string ModifiedBy { get; set; }
        public string HODPurDeptApprovalBy { get; set; }
        public Nullable<System.DateTime> HODPurDeptApprovalDate { get; set; }
        public string MDApprovalBy { get; set; }
        public Nullable<System.DateTime> MDApprovalDate { get; set; }
        public Nullable<decimal> GrandAmt { get; set; }
        public string AccountCode { get; set; }
        public string HODComment { get; set; }
        public Nullable<int> FileId { get; set; }
        public string Purpose { get; set; }
        public string Remarks { get; set; }
        public string CPRF { get; set; }
        public Nullable<int> AssetFlag { get; set; }
        public Nullable<decimal> AssetBudget { get; set; }
        public Nullable<decimal> AssetBal { get; set; }
        public Nullable<bool> FlagUpdatedCPRF { get; set; }
        public Nullable<bool> FlagUpdateMonthlyBudget { get; set; }
        public Nullable<int> PRGroupType { get; set; }
        public string HODPurComment { get; set; }
        public string PurchaserName { get; set; }
        public Nullable<System.DateTime> SendHODPurDate { get; set; }
        public string AssetNo { get; set; }
        public string IOrderNo { get; set; }
        public string CostCentreNo { get; set; }
        public string ItemNo { get; set; }
        public string VendorItemNo { get; set; }
        public Nullable<System.DateTime> SendToProcessingDate { get; set; }
        public string PurchasingComment { get; set; }
        public Nullable<int> BudgetDept { get; set; }
        public string SourcingName { get; set; }
        public Nullable<bool> DeActiveFlag { get; set; }
        public string TeamId { get; set; }
        public string VendorCodeDiscount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string VendorNameDiscount { get; set; }
        public string VendorCurrDiscount { get; set; }
        public string RejectCommentClerk { get; set; }
        public string RejectCommentClerktoUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_Details> PR_Details { get; set; }
        public virtual Department_mst Department_mst { get; set; }
        public virtual Usr_mst Usr_mst { get; set; }
        public virtual Status_Mst Status_Mst { get; set; }
        public virtual PRType_mst PRType_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRFile> PRFiles { get; set; }
        public virtual AccTypeDept AccTypeDept { get; set; }
        public virtual PrGroupType PrGroupType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PO_Mst> PO_Mst { get; set; }
    }
}
