//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_VendorComparison
    {
        public int VCId { get; set; }
        public Nullable<int> PRDtId { get; set; }
        public string VCName { get; set; }
        public Nullable<decimal> CurPrice { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<System.DateTime> LastQuoteDate { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> CostDown { get; set; }
        public Nullable<bool> FlagWin { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> TotCostnoTax { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<decimal> TotCostWitTax { get; set; }
        public string TaxCode { get; set; }
        public Nullable<int> TaxClass { get; set; }
        public string VDCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> DiscType { get; set; }
        public Nullable<decimal> CurRate { get; set; }
        public string VdCurCode { get; set; }
        public Nullable<decimal> TotCostnoTaxVendorCur { get; set; }
        public Nullable<decimal> TotCostWitTaxVendorCur { get; set; }
        public Nullable<decimal> CurPriceMYR { get; set; }
        public string PayTerms { get; set; }
        public string PayDesc { get; set; }
        public string QuoteName { get; set; }
        public string QuotePath { get; set; }
        public string QuoteNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual PR_Details PR_Details { get; set; }
    }
}
