//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrTypeMap
    {
        public int PRTypeMapId { get; set; }
        public Nullable<int> PRType { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual PrGroupType PrGroupType { get; set; }
    }
}
