//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMenuMapping_mst
    {
        public int RoleMap_Id { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Menu_mst Menu_mst { get; set; }
        public virtual Position_mst Position_mst { get; set; }
    }
}
