//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dom1Entities : DbContext
    {
        public dom1Entities()
            : base("name=dom1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APVEN> APVENs { get; set; }
        public virtual DbSet<CSCCD> CSCCDs { get; set; }
        public virtual DbSet<ICITMV> ICITMVs { get; set; }
        public virtual DbSet<ICUCOD> ICUCODs { get; set; }
        public virtual DbSet<POVIA> POVIAs { get; set; }
        public virtual DbSet<POVUPR> POVUPRs { get; set; }
        public virtual DbSet<CSCRD> CSCRDs { get; set; }
        public virtual DbSet<APRTA> APRTAs { get; set; }
        public virtual DbSet<APVENO> APVENOes { get; set; }
        public virtual DbSet<AMCATE> AMCATEs { get; set; }
        public virtual DbSet<AMASST> AMASSTs { get; set; }
    }
}
