//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu_mst
    {
        public int SubMenu_id { get; set; }
        public string SubMenu_Name { get; set; }
        public Nullable<bool> Flag { get; set; }
        public Nullable<int> Menu_id { get; set; }
    }
}
