//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usr_mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usr_mst()
        {
            this.PR_Details = new HashSet<PR_Details>();
            this.PR_Mst = new HashSet<PR_Mst>();
            this.HODManager_Map = new HashSet<HODManager_Map>();
            this.HODManager_Map1 = new HashSet<HODManager_Map>();
        }
    
        public int usr_id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<int> Dpt_id { get; set; }
        public Nullable<int> Psn_id { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_modified { get; set; }
        public Nullable<bool> Flag_Aproval { get; set; }
        public string TelExt { get; set; }
        public Nullable<bool> SourcingFlag { get; set; }
        public string Team_id { get; set; }
        public Nullable<bool> MD_PA_Flag { get; set; }
    
        public virtual Department_mst Department_mst { get; set; }
        public virtual Position_mst Position_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_Details> PR_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PR_Mst> PR_Mst { get; set; }
        public virtual AccTypeDept AccTypeDept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HODManager_Map> HODManager_Map { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HODManager_Map> HODManager_Map1 { get; set; }
    }
}
