//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usr_mst
    {
        [Key]
        public int usr_id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<int> Dpt_id { get; set; }
        public Nullable<int> Psn_id { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public Nullable<System.DateTime> Date_modified { get; set; }
        public Nullable<bool> Flag_Aproval { get; set; }
    
        public virtual Department_mst Department_mst { get; set; }
        public virtual Position_mst Position_mst { get; set; }
    }
}
