//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseWeb_2.ModelData
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CprfDept
    {
        public Nullable<int> DepartmentId { get; set; }
        public string DeptName { get; set; }
        public string DeptCode { get; set; }
        public int AccTypeDepID { get; set; }
    }
}
